/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/eligibility_inquiries": {
    /** Get a complete list of the eligibility inquiries that you have created in the past. */
    get: operations["getEligibilityInquiries"];
    /** Create a new eligibility inquiry for the given plan, provider and subscriber. The response should indicate whether the subscriber is eligible for any services offered by provider under this plan. */
    post: operations["postEligibilityInquiries"];
  };
  "/v1/eligibility_inquiries/{id}": {
    /** Get a single eligibility inquiry that you have created in the past. */
    get: operations["getEligibilityInquiriesId"];
  };
  "/v1/payers": {
    /** Get a complete list of the payers supported by Opkit. */
    get: operations["getPayers"];
  };
}

export interface components {
  schemas: {
    /** @description A request for information from a payer about a health insurance policy's coverages, typically in relation to a particular subscriber. */
    EligibilityInquiry: {
      /** @description A unique identifier */
      id: string;
    };
    /** @description A health insurance carrier, which may offer more than one policy. */
    Payer: {
      /** @description A unique identifier */
      id: string;
    };
    /** @description A healthcare provider, which is assigned a National Provider Identifier, or NPI. This can be an individual or an organization. */
    Provider: {
      /** @description The name of this provider organization. */
      organization_name: string;
      /** @description The provider's NPI number. */
      npi: string;
    };
    /** @description An individual member of a health insurance policy. An insured person. */
    Subscriber: {
      /** @description The insured person's first name, as it appears on their insurance card. */
      first_name: string;
      /** @description The insured person's last name, as it appears on their insurance card. */
      last_name: string;
      /** @description The insured person's member ID, as it appears on their insurance card. */
      member_id: string;
      /** @description The insured person's gender, as it appears on their insurance card. */
      gender: string;
      /**
       * Format: date
       * @description The insured person's date of birth, as it appears on their insurance card.
       */
      date_of_birth: string;
    };
    /** @description An object representing an encounter or interaction between a patient and provider, during which medical services may be performed. */
    Encounter: {
      /**
       * Format: date
       * @description The date of this particular patient encounter.
       */
      date_of_service: string;
      /** @description A list of service type codes. */
      service_type_codes: string[];
    };
    /** @description An object that is returned when an error has occured. */
    Error: {
      /** @description A unique error code indicating what went wrong. */
      code: string;
      /** @description A brief text description that expands upon this particular error code. */
      message: string;
    };
  };
  responses: {
    /** A default error response if no other response is provided. */
    Default: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
}

export interface operations {
  /** Get a complete list of the eligibility inquiries that you have created in the past. */
  getEligibilityInquiries: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            /** @description The number of items in this list */
            count: number;
            /** @description A list of eligibility inquiries */
            items: components["schemas"]["EligibilityInquiry"][];
          };
        };
      };
      default: components["responses"]["Default"];
    };
  };
  /** Create a new eligibility inquiry for the given plan, provider and subscriber. The response should indicate whether the subscriber is eligible for any services offered by provider under this plan. */
  postEligibilityInquiries: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["EligibilityInquiry"];
        };
      };
      default: components["responses"]["Default"];
    };
    /** A payload containing the payer_id, provider, subscriber and encounter information that is relevant for this eligibility inquiry. */
    requestBody: {
      content: {
        "application/json": {
          /** @description The ID of the insurance plan that should receive the inquiry */
          payer_id: string;
          provider: components["schemas"]["Provider"];
          subscriber: components["schemas"]["Subscriber"];
          encounter: components["schemas"]["Encounter"];
        };
      };
    };
  };
  /** Get a single eligibility inquiry that you have created in the past. */
  getEligibilityInquiriesId: {
    parameters: {
      path: {
        /** Numeric ID of the eligibility inquiry to get */
        id: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["EligibilityInquiry"];
        };
      };
      default: components["responses"]["Default"];
    };
  };
  /** Get a complete list of the payers supported by Opkit. */
  getPayers: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            /** @description The number of items in this list. */
            count: number;
            /** @description A list of payers. */
            items: components["schemas"]["Payer"][];
          };
        };
      };
      default: components["responses"]["Default"];
    };
  };
}

export interface external {}
